/* 
 * Fiscaal Gemak API
 *
 * Fiscaal Gemak API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jpt@sultancrm.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ClientContactPerson
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ClientContactPersonTests
    {
        // TODO uncomment below to declare an instance variable for ClientContactPerson
        //private ClientContactPerson instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ClientContactPerson
            //instance = new ClientContactPerson();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ClientContactPerson
        /// </summary>
        [Test]
        public void ClientContactPersonInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ClientContactPerson
            //Assert.IsInstanceOfType<ClientContactPerson> (instance, "variable 'instance' is a ClientContactPerson");
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Initials'
        /// </summary>
        [Test]
        public void InitialsTest()
        {
            // TODO unit test for the property 'Initials'
        }
        /// <summary>
        /// Test the property 'Prefix'
        /// </summary>
        [Test]
        public void PrefixTest()
        {
            // TODO unit test for the property 'Prefix'
        }
        /// <summary>
        /// Test the property 'Surname'
        /// </summary>
        [Test]
        public void SurnameTest()
        {
            // TODO unit test for the property 'Surname'
        }
        /// <summary>
        /// Test the property 'TelephoneNumber'
        /// </summary>
        [Test]
        public void TelephoneNumberTest()
        {
            // TODO unit test for the property 'TelephoneNumber'
        }

    }

}
