#region Copyright (c) 2000-2020 Sultan CRM BV

// ===========================================================
// 
// MIT License
// 
// Copyright (c) 2020 Sultan CRM B.V. / Jean Paul Teunisse
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// ===========================================================

#endregion

#region usings

using NUnit.Framework;

#endregion

namespace FG.Api.Test {
    /// <summary>
    ///  Class for testing ClientAddresses
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ClientAddressesTests {
        // TODO uncomment below to declare an instance variable for ClientAddresses
        //private ClientAddresses instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init() {
            // TODO uncomment below to create an instance of ClientAddresses
            //instance = new ClientAddresses();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup() {
        }


        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest() {
            // TODO unit test for the property 'City'
        }

        /// <summary>
        /// Test an instance of ClientAddresses
        /// </summary>
        [Test]
        public void ClientAddressesInstanceTest() {
            // TODO uncomment below to test "IsInstanceOfType" ClientAddresses
            //Assert.IsInstanceOfType<ClientAddresses> (instance, "variable 'instance' is a ClientAddresses");
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest() {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'Postcode'
        /// </summary>
        [Test]
        public void PostcodeTest() {
            // TODO unit test for the property 'Postcode'
        }

        /// <summary>
        /// Test the property 'StreetNumberAddition'
        /// </summary>
        [Test]
        public void StreetNumberAdditionTest() {
            // TODO unit test for the property 'StreetNumberAddition'
        }

        /// <summary>
        /// Test the property 'StreetNumber'
        /// </summary>
        [Test]
        public void StreetNumberTest() {
            // TODO unit test for the property 'StreetNumber'
        }

        /// <summary>
        /// Test the property 'Street'
        /// </summary>
        [Test]
        public void StreetTest() {
            // TODO unit test for the property 'Street'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest() {
            // TODO unit test for the property 'Type'
        }
    }
}