#region Copyright (c) 2000-2020 Sultan CRM BV

// ===========================================================
// 
// MIT License
// 
// Copyright (c) 2020 Sultan CRM B.V. / Jean Paul Teunisse
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// ===========================================================

#endregion

#region usings

using NUnit.Framework;

#endregion

namespace FG.Api.Test {
    /// <summary>
    ///  Class for testing ClientContactPerson
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ClientContactPersonTests {
        // TODO uncomment below to declare an instance variable for ClientContactPerson
        //private ClientContactPerson instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init() {
            // TODO uncomment below to create an instance of ClientContactPerson
            //instance = new ClientContactPerson();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup() {
        }

        /// <summary>
        /// Test an instance of ClientContactPerson
        /// </summary>
        [Test]
        public void ClientContactPersonInstanceTest() {
            // TODO uncomment below to test "IsInstanceOfType" ClientContactPerson
            //Assert.IsInstanceOfType<ClientContactPerson> (instance, "variable 'instance' is a ClientContactPerson");
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest() {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Initials'
        /// </summary>
        [Test]
        public void InitialsTest() {
            // TODO unit test for the property 'Initials'
        }

        /// <summary>
        /// Test the property 'Prefix'
        /// </summary>
        [Test]
        public void PrefixTest() {
            // TODO unit test for the property 'Prefix'
        }

        /// <summary>
        /// Test the property 'Surname'
        /// </summary>
        [Test]
        public void SurnameTest() {
            // TODO unit test for the property 'Surname'
        }

        /// <summary>
        /// Test the property 'TelephoneNumber'
        /// </summary>
        [Test]
        public void TelephoneNumberTest() {
            // TODO unit test for the property 'TelephoneNumber'
        }
    }
}