#region Copyright (c) 2000-2020 Sultan CRM BV

// ===========================================================
// 
// MIT License
// 
// Copyright (c) 2020 Sultan CRM B.V. / Jean Paul Teunisse
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// ===========================================================

#endregion

#region usings

using NUnit.Framework;

#endregion

namespace FG.Api.Test {
    /// <summary>
    ///  Class for testing ModelClient
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelClientTests {
        // TODO uncomment below to declare an instance variable for ModelClient
        //private ModelClient instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init() {
            // TODO uncomment below to create an instance of ModelClient
            //instance = new ModelClient();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup() {
        }


        /// <summary>
        /// Test the property 'Addresses'
        /// </summary>
        [Test]
        public void AddressesTest() {
            // TODO unit test for the property 'Addresses'
        }

        /// <summary>
        /// Test the property 'BeconNumber'
        /// </summary>
        [Test]
        public void BeconNumberTest() {
            // TODO unit test for the property 'BeconNumber'
        }

        /// <summary>
        /// Test the property 'BirthDate'
        /// </summary>
        [Test]
        public void BirthDateTest() {
            // TODO unit test for the property 'BirthDate'
        }

        /// <summary>
        /// Test the property 'ChamberOfCommerceNumber'
        /// </summary>
        [Test]
        public void ChamberOfCommerceNumberTest() {
            // TODO unit test for the property 'ChamberOfCommerceNumber'
        }

        /// <summary>
        /// Test the property 'ClientGroupIsVip'
        /// </summary>
        [Test]
        public void ClientGroupIsVipTest() {
            // TODO unit test for the property 'ClientGroupIsVip'
        }

        /// <summary>
        /// Test the property 'ClientGroupName'
        /// </summary>
        [Test]
        public void ClientGroupNameTest() {
            // TODO unit test for the property 'ClientGroupName'
        }

        /// <summary>
        /// Test the property 'ContactPerson'
        /// </summary>
        [Test]
        public void ContactPersonTest() {
            // TODO unit test for the property 'ContactPerson'
        }

        /// <summary>
        /// Test the property 'DateStartCustomerRelation'
        /// </summary>
        [Test]
        public void DateStartCustomerRelationTest() {
            // TODO unit test for the property 'DateStartCustomerRelation'
        }

        /// <summary>
        /// Test the property 'DeceasedDate'
        /// </summary>
        [Test]
        public void DeceasedDateTest() {
            // TODO unit test for the property 'DeceasedDate'
        }

        /// <summary>
        /// Test the property 'EmailAddresses'
        /// </summary>
        [Test]
        public void EmailAddressesTest() {
            // TODO unit test for the property 'EmailAddresses'
        }

        /// <summary>
        /// Test the property 'IdentificationNumber'
        /// </summary>
        [Test]
        public void IdentificationNumberTest() {
            // TODO unit test for the property 'IdentificationNumber'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest() {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Initials'
        /// </summary>
        [Test]
        public void InitialsTest() {
            // TODO unit test for the property 'Initials'
        }

        /// <summary>
        /// Test an instance of ModelClient
        /// </summary>
        [Test]
        public void ModelClientInstanceTest() {
            // TODO uncomment below to test "IsInstanceOfType" ModelClient
            //Assert.IsInstanceOfType<ModelClient> (instance, "variable 'instance' is a ModelClient");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest() {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Test]
        public void NumberTest() {
            // TODO unit test for the property 'Number'
        }

        /// <summary>
        /// Test the property 'PhoneNumbers'
        /// </summary>
        [Test]
        public void PhoneNumbersTest() {
            // TODO unit test for the property 'PhoneNumbers'
        }

        /// <summary>
        /// Test the property 'Prefix'
        /// </summary>
        [Test]
        public void PrefixTest() {
            // TODO unit test for the property 'Prefix'
        }

        /// <summary>
        /// Test the property 'Salutation'
        /// </summary>
        [Test]
        public void SalutationTest() {
            // TODO unit test for the property 'Salutation'
        }

        /// <summary>
        /// Test the property 'Surname'
        /// </summary>
        [Test]
        public void SurnameTest() {
            // TODO unit test for the property 'Surname'
        }

        /// <summary>
        /// Test the property 'TaxConsultant'
        /// </summary>
        [Test]
        public void TaxConsultantTest() {
            // TODO unit test for the property 'TaxConsultant'
        }

        /// <summary>
        /// Test the property 'TypeOfBusinessEntity'
        /// </summary>
        [Test]
        public void TypeOfBusinessEntityTest() {
            // TODO unit test for the property 'TypeOfBusinessEntity'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest() {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'VatNumber'
        /// </summary>
        [Test]
        public void VatNumberTest() {
            // TODO unit test for the property 'VatNumber'
        }
    }
}