/* 
 * Fiscaal Gemak API
 *
 * Fiscaal Gemak API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jpt@sultancrm.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FG.Api.Api;
using FG.Api.Model;
using FG.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FG.Api.Test
{
    /// <summary>
    ///  Class for testing ModelClient
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelClientTests
    {
        // TODO uncomment below to declare an instance variable for ModelClient
        //private ModelClient instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelClient
            //instance = new ModelClient();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelClient
        /// </summary>
        [Test]
        public void ModelClientInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelClient
            //Assert.IsInstanceOfType<ModelClient> (instance, "variable 'instance' is a ModelClient");
        }


        /// <summary>
        /// Test the property 'Addresses'
        /// </summary>
        [Test]
        public void AddressesTest()
        {
            // TODO unit test for the property 'Addresses'
        }
        /// <summary>
        /// Test the property 'BeconNumber'
        /// </summary>
        [Test]
        public void BeconNumberTest()
        {
            // TODO unit test for the property 'BeconNumber'
        }
        /// <summary>
        /// Test the property 'BirthDate'
        /// </summary>
        [Test]
        public void BirthDateTest()
        {
            // TODO unit test for the property 'BirthDate'
        }
        /// <summary>
        /// Test the property 'ChamberOfCommerceNumber'
        /// </summary>
        [Test]
        public void ChamberOfCommerceNumberTest()
        {
            // TODO unit test for the property 'ChamberOfCommerceNumber'
        }
        /// <summary>
        /// Test the property 'ClientGroupIsVip'
        /// </summary>
        [Test]
        public void ClientGroupIsVipTest()
        {
            // TODO unit test for the property 'ClientGroupIsVip'
        }
        /// <summary>
        /// Test the property 'ClientGroupName'
        /// </summary>
        [Test]
        public void ClientGroupNameTest()
        {
            // TODO unit test for the property 'ClientGroupName'
        }
        /// <summary>
        /// Test the property 'DateStartCustomerRelation'
        /// </summary>
        [Test]
        public void DateStartCustomerRelationTest()
        {
            // TODO unit test for the property 'DateStartCustomerRelation'
        }
        /// <summary>
        /// Test the property 'DeceasedDate'
        /// </summary>
        [Test]
        public void DeceasedDateTest()
        {
            // TODO unit test for the property 'DeceasedDate'
        }
        /// <summary>
        /// Test the property 'ContactPerson'
        /// </summary>
        [Test]
        public void ContactPersonTest()
        {
            // TODO unit test for the property 'ContactPerson'
        }
        /// <summary>
        /// Test the property 'EmailAddresses'
        /// </summary>
        [Test]
        public void EmailAddressesTest()
        {
            // TODO unit test for the property 'EmailAddresses'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'IdentificationNumber'
        /// </summary>
        [Test]
        public void IdentificationNumberTest()
        {
            // TODO unit test for the property 'IdentificationNumber'
        }
        /// <summary>
        /// Test the property 'Initials'
        /// </summary>
        [Test]
        public void InitialsTest()
        {
            // TODO unit test for the property 'Initials'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Test]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'PhoneNumbers'
        /// </summary>
        [Test]
        public void PhoneNumbersTest()
        {
            // TODO unit test for the property 'PhoneNumbers'
        }
        /// <summary>
        /// Test the property 'Prefix'
        /// </summary>
        [Test]
        public void PrefixTest()
        {
            // TODO unit test for the property 'Prefix'
        }
        /// <summary>
        /// Test the property 'Salutation'
        /// </summary>
        [Test]
        public void SalutationTest()
        {
            // TODO unit test for the property 'Salutation'
        }
        /// <summary>
        /// Test the property 'VatNumber'
        /// </summary>
        [Test]
        public void VatNumberTest()
        {
            // TODO unit test for the property 'VatNumber'
        }
        /// <summary>
        /// Test the property 'Surname'
        /// </summary>
        [Test]
        public void SurnameTest()
        {
            // TODO unit test for the property 'Surname'
        }
        /// <summary>
        /// Test the property 'TaxConsultant'
        /// </summary>
        [Test]
        public void TaxConsultantTest()
        {
            // TODO unit test for the property 'TaxConsultant'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'TypeOfBusinessEntity'
        /// </summary>
        [Test]
        public void TypeOfBusinessEntityTest()
        {
            // TODO unit test for the property 'TypeOfBusinessEntity'
        }

    }

}
